# version: '2'
# services:
#   users-service:
#     build: ./nuxtapp
#     container_name: nuxtapp
#     ports:
#      - "3000:3000"
#     links:
#       - db:db
#     depends_on:
#      - db
#     environment:
#      - DATABASE_HOST=127.0.0.1
#   db:
#     build: ./db
#     ports:
#      - "3306:3306"
version: '3'

services:
  users-service:
    build: ./nuxtapp
    container_name: nuxtapp
    ports:
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    networks:
     - mynetwork

  db:
    build: ./db
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
     - db-data:/var/lib/mysql
    networks:
     - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data: